name: "build"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
          repository: bertbesser/dreamscrape-scrape
          tag_with_ref: true
          push: true
          tags: bertbesser/dreamscrape-scrape:latest
